repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    files: \.py$
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    files: \.py$
  - id: pytest
    name: pytest
    entry: pytest
    language: system
    pass_filenames: false