repos:
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    files: \.py$
  - id: pytest
    name: pytest
    entry: pytest
    language: system
    types: [python]